# Site
name: "Terry's Site"
title: "Terry's Site"
description: "hi"
logo: 'assets/images/logo.ico'
favicon: 'assets/images/logo.ico'
baseurl: ''
google_analytics: 'UA-46278016-1'
disqus: 'tianyu_hu'
mailchimp-list: 'huty1998@outlook.com'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  terry:
    name: Terry
    display_name: Terry
    avatar: 'assets/images/cousins.jpg'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: huty1998@outlook.com
    web: https://huty1998.github.io/
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
